/*$file${.::dpp_comp.ino} ##################################################*/
/*
* Model: dpp_comp.qm
* File:  ${.::dpp_comp.ino}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::dpp_comp.ino} ###############################################*/
#include "qpn.h"     // QP-nano framework
#include "Arduino.h" // Arduino API

Q_DEFINE_THIS_MODULE("dpp")

//============================================================================
enum DPPSignals {
    TICK_SIG = Q_USER_SIG, // posted by system clock tick ISR to Table
    EAT_SIG,              // posted by Table to let a philosopher eat
    DONE_SIG,             // posted by Philosopher when done eating
    PAUSE_SIG,            // posted by BSP to pause the application
    SERVE_SIG,            // posted by BSP to pause the application
    HUNGRY_SIG,           // posted to Table from hungry Philo
    MAX_SIG               // the last signal
};

enum {
    N_PHILO = 10 // number of Philosophers
};

//============================================================================
// declare the Philo components...
/*$declare${AOs::Philo} ####################################################*/
/*${AOs::Philo} ............................................................*/
typedef struct Philo {
/* protected: */
    QHsm super;

/* public: */
    uint16_t tickCtr;
    uint8_t num;
} Philo;

/* public: */
static void Philo_ctor(Philo * const me, uint8_t num);

/* protected: */
static QState Philo_initial(Philo * const me);
static QState Philo_thinking(Philo * const me);
static QState Philo_hungry(Philo * const me);
static QState Philo_eating(Philo * const me);
/*$enddecl${AOs::Philo} ####################################################*/

// declare all AO classes...
/*$declare${AOs::Table} ####################################################*/
/*${AOs::Table} ............................................................*/
typedef struct Table {
/* protected: */
    QActive super;

/* private: */
    Philo philo_pool[N_PHILO];
    uint8_t fork[N_PHILO];
    uint8_t isHungry[N_PHILO];
} Table;

/* protected: */
static QState Table_initial(Table * const me);
static QState Table_active(Table * const me);
static QState Table_serving(Table * const me);
static QState Table_paused(Table * const me);
/*$enddecl${AOs::Table} ####################################################*/
/*$declare${AOs::Table_ctor} ###############################################*/
/*${AOs::Table_ctor} .......................................................*/
static void Table_ctor(void);
/*$enddecl${AOs::Table_ctor} ###############################################*/
//...

// define all AO instances and event queue buffers for them...
Table AO_Table;
static QEvt l_tableQueue[3 + N_PHILO];
//...

//============================================================================
// QF_active[] array defines all active object control blocks ----------------
QActiveCB const Q_ROM QF_active[] = {
    { (QActive *)0,            (QEvt *)0,        0U                      },
    { (QActive *)&AO_Table,    l_tableQueue,     Q_DIM(l_tableQueue)     }
};

//============================================================================
// Board Support Package

// various other constants for the application...
enum {
    BSP_TICKS_PER_SEC = 100, // number of system clock ticks in one second
    LED_L             = 13,  // the pin number of the on-board LED (L)
    PHILO_0_PRIO      = 1,   // priority of the first Philo AO
    THINK_TIME        = 3*BSP_TICKS_PER_SEC, // time for thinking
    EAT_TIME          = 2*BSP_TICKS_PER_SEC  // time for eating
};

//............................................................................
void BSP_displayPhilStat(uint8_t n, char_t const *stat) {
    if (stat[0] == 'e') {
        digitalWrite(LED_L, HIGH);
    }
    else {
        digitalWrite(LED_L, LOW);
    }

    Serial.print(F("Philo["));
    Serial.print(n, DEC);
    Serial.print(F("] "));
    Serial.println(stat);
}
//............................................................................
void BSP_displayPaused(uint8_t paused) {
    if (paused) {
        Serial.println(F("Paused ON"));
    }
    else {
        Serial.println(F("Paused OFF"));
    }
}

//............................................................................
void setup() {
    // initialize the QF-nano framework
    QF_init(Q_DIM(QF_active));

    // instantiate all active objects...
    Table_ctor();

    // initialize the hardware used in this sketch...
    pinMode(LED_L, OUTPUT); // set the LED-L pin to output

    Serial.begin(115200);   // set the highest stanard baud rate of 115200 bps
    Serial.print(F("QP-nano: "));
    Serial.print(F(QP_VERSION_STR));
    Serial.println(F(""));
}

//............................................................................
void loop() {
    QF_run(); // run the QP-nano application
}

//============================================================================
// interrupts
ISR(TIMER2_COMPA_vect) {
    QF_tickXISR(0); // process time events for tick rate 0

    // post the TICK_SIG event to the Table AO every system clock tick
    QACTIVE_POST_X_ISR(&AO_Table,
                       3U, // leave a margin of 3 entries in the queue
                       TICK_SIG, 0U);

    if (Serial.available() > 0) {
        switch (Serial.read()) { // read the incoming byte
            case 'p':
            case 'P':
                QACTIVE_POST_ISR(&AO_Table, PAUSE_SIG, 0U);
                break;
            case 's':
            case 'S':
                QACTIVE_POST_ISR(&AO_Table, SERVE_SIG, 0U);
                break;
        }
    }
}

//============================================================================
// QF callbacks...
void QF_onStartup(void) {
    // set Timer2 in CTC mode, 1/1024 prescaler, start the timer ticking...
    TCCR2A = (1U << WGM21) | (0U << WGM20);
    TCCR2B = (1U << CS22 ) | (1U << CS21) | (1U << CS20); // 1/2^10
    ASSR  &= ~(1U << AS2);
    TIMSK2 = (1U << OCIE2A); // enable TIMER2 compare Interrupt
    TCNT2  = 0U;

    // set the output-compare register based on the desired tick frequency
    OCR2A  = (F_CPU / BSP_TICKS_PER_SEC / 1024U) - 1U;
}
//............................................................................
void QV_onIdle(void) {   // called with interrupts DISABLED
    // Put the CPU and peripherals to the low-power mode. You might
    // need to customize the clock management for your application,
    // see the datasheet for your particular AVR MCU.
#ifdef NDEBUG
    SMCR = (0 << SM0) | (1 << SE); // idle mode, adjust to your project
    QV_CPU_SLEEP();  // atomically go to sleep and enable interrupts
#else
    QF_INT_ENABLE();
#endif
}
//............................................................................
void Q_onAssert(char const Q_ROM * const module, int line) {
    // implement the error-handling policy for your application!!!
    //Serial.print(F("Assert: "));
    Serial.print(reinterpret_cast<const __FlashStringHelper *>(module));
    Serial.println(line, DEC);
    delay(200);

    QF_INT_DISABLE(); // disable all interrupts
    QF_RESET();  // reset the CPU
}

//============================================================================
// define the components...
/*$define${AOs::Philo} #####################################################*/
/* Check for the minimum required QP version */
#if ((QP_VERSION < 601) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 6.0.1 or higher required
#endif
/*${AOs::Philo} ............................................................*/
/*${AOs::Philo::ctor} ......................................................*/
static void Philo_ctor(Philo * const me, uint8_t num) {
    QHsm_ctor(&me->super, Q_STATE_CAST(&Philo_initial));
    me->num = num;
}

/*${AOs::Philo::SM} ........................................................*/
static QState Philo_initial(Philo * const me) {
    /*${AOs::Philo::SM::initial} */
    me->tickCtr = 0U;
    return Q_TRAN(&Philo_thinking);
}
/*${AOs::Philo::SM::thinking} ..............................................*/
static QState Philo_thinking(Philo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Philo::SM::thinking} */
        case Q_ENTRY_SIG: {
            me->tickCtr = THINK_TIME;
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Philo::SM::thinking} */
        case Q_EXIT_SIG: {
            me->tickCtr = 0U;
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Philo::SM::thinking::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Philo_hungry);
            break;
        }
        /*${AOs::Philo::SM::thinking::EAT, DONE} */
        case EAT_SIG: /* intentionally fall through */
        case DONE_SIG: {
            Q_ERROR(); /* these events should never arrive in this state */
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Philo::SM::hungry} ................................................*/
static QState Philo_hungry(Philo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Philo::SM::hungry} */
        case Q_ENTRY_SIG: {
            QACTIVE_POST(&AO_Table, HUNGRY_SIG, me->num);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Philo::SM::hungry::EAT} */
        case EAT_SIG: {
            status_ = Q_TRAN(&Philo_eating);
            break;
        }
        /*${AOs::Philo::SM::hungry::DONE} */
        case DONE_SIG: {
            Q_ERROR(); /* this event should never arrive in this state */
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Philo::SM::eating} ................................................*/
static QState Philo_eating(Philo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Philo::SM::eating} */
        case Q_ENTRY_SIG: {
            me->tickCtr = EAT_TIME;
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Philo::SM::eating} */
        case Q_EXIT_SIG: {
            me->tickCtr = 0U;
            QACTIVE_POST(&AO_Table, DONE_SIG, me->num);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Philo::SM::eating::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Philo_thinking);
            break;
        }
        /*${AOs::Philo::SM::eating::EAT, DONE} */
        case EAT_SIG: /* intentionally fall through */
        case DONE_SIG: {
            Q_ERROR(); /* these events should never arrive in this state */
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Philo} #####################################################*/

//============================================================================
// define all AO classes...
static inline uint8_t RIGHT(uint8_t n) {
    return (n + (N_PHILO - 1)) % N_PHILO;
}
static inline uint8_t LEFT(uint8_t n) {
    return (n + 1) % N_PHILO;
}
enum {
    FREE = 0,
    USED = 1
};

/*$define${AOs::Table} #####################################################*/
/*${AOs::Table} ............................................................*/
/*${AOs::Table::SM} ........................................................*/
static QState Table_initial(Table * const me) {
    /*${AOs::Table::SM::initial} */
    uint8_t n;
    for (n = 0U; n < N_PHILO; ++n) {
        QHSM_INIT(&me->philo_pool[n].super);
        me->fork[n] = FREE;
        me->isHungry[n] = 0U;
        BSP_displayPhilStat(n, "thinking");
    }
    return Q_TRAN(&Table_serving);
}
/*${AOs::Table::SM::active} ................................................*/
static QState Table_active(Table * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Table::SM::active::EAT} */
        case EAT_SIG: {
            Q_ERROR();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Table::SM::active::TICK} */
        case TICK_SIG: {
            uint8_t n;
            for (n = 0U; n < N_PHILO; ++n) { // for all "Philo" components...
                Philo *philo = &me->philo_pool[n];
                if (philo->tickCtr != 0U) { // is the "Philo" tick counter runnning?
                    if (--philo->tickCtr == 0U) { // is the "Philo" tick expiring?
                        // synchronously dispatch to component
                        Q_SIG(philo) = Q_TIMEOUT_SIG;
                        QHSM_DISPATCH(&philo->super);
                    }
                }
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Table::SM::active::serving} .......................................*/
static QState Table_serving(Table * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Table::SM::active::serving} */
        case Q_ENTRY_SIG: {
            uint8_t n;
            for (n = 0U; n < N_PHILO; ++n) { /* give permissions to eat... */
                if ((me->isHungry[n] != 0U)
                    && (me->fork[LEFT(n)] == FREE)
                    && (me->fork[n] == FREE))
                {
                    me->fork[LEFT(n)] = USED;
                    me->fork[n] = USED;

                    /* synchronously dispatch to philo_pool[n] */
                    Q_SIG(&me->philo_pool[n]) = EAT_SIG;
                    Q_PAR(&me->philo_pool[n]) = n;
                    QHSM_DISPATCH(&me->philo_pool[n].super);

                    me->isHungry[n] = 0U;
                    BSP_displayPhilStat(n, "eating  ");
                }
            }
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Table::SM::active::serving::HUNGRY} */
        case HUNGRY_SIG: {
            uint8_t n, m;

            n = (uint8_t)Q_PAR(me);

            BSP_displayPhilStat(n, "hungry  ");

            /* philo ID must be in range and he must be not hungry */
            Q_ASSERT((n < N_PHILO) && (me->isHungry[n] == 0U));

            m = LEFT(n);
            /*${AOs::Table::SM::active::serving::HUNGRY::[both-free]} */
            if ((me->fork[m] == FREE) && (me->fork[n] == FREE)) {
                me->fork[m] = USED;
                me->fork[n] = USED;

                /* synchronously dispatch to philo_pool[n] */
                Q_SIG(&me->philo_pool[n]) = EAT_SIG;
                Q_PAR(&me->philo_pool[n]) = n;
                QHSM_DISPATCH(&me->philo_pool[n].super);

                BSP_displayPhilStat(n, "eating  ");
                status_ = Q_HANDLED();
            }
            /*${AOs::Table::SM::active::serving::HUNGRY::[else]} */
            else {
                me->isHungry[n] = 1U;
                status_ = Q_HANDLED();
            }
            break;
        }
        /*${AOs::Table::SM::active::serving::DONE} */
        case DONE_SIG: {
            uint8_t n, m;

            n = (uint8_t)Q_PAR(me);

            /* phil ID must be in range and he must be not hungry */
            Q_ASSERT((n < N_PHILO) && (me->isHungry[n] == 0U));

            BSP_displayPhilStat(n, "thinking");
            m = LEFT(n);
            /* both forks of Philo[n] must be used */
            Q_ASSERT((me->fork[n] == USED) && (me->fork[m] == USED));

            me->fork[m] = FREE;
            me->fork[n] = FREE;
            m = RIGHT(n); /* check the right neighbor */

            if ((me->isHungry[m] != 0U) && (me->fork[m] == FREE)) {
                me->fork[n] = USED;
                me->fork[m] = USED;
                me->isHungry[m] = 0U;

                /* synchronously dispatch to philo_pool[m] */
                Q_SIG(&me->philo_pool[m]) = EAT_SIG;
                Q_PAR(&me->philo_pool[m]) = m;
                QHSM_DISPATCH(&me->philo_pool[m].super);

                BSP_displayPhilStat(m, "eating  ");
            }
            m = LEFT(n); /* check the left neighbor */
            n = LEFT(m); /* left fork of the left neighbor */
            if ((me->isHungry[m] != 0U) && (me->fork[n] == FREE)) {
                me->fork[m] = USED;
                me->fork[n] = USED;
                me->isHungry[m] = 0U;

                /* synchronously dispatch to philo_pool[m] */
                Q_SIG(&me->philo_pool[m]) = EAT_SIG;
                Q_PAR(&me->philo_pool[m]) = m;
                QHSM_DISPATCH(&me->philo_pool[m].super);

                BSP_displayPhilStat(m, "eating  ");
            }
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Table::SM::active::serving::EAT} */
        case EAT_SIG: {
            Q_ERROR();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Table::SM::active::serving::PAUSE} */
        case PAUSE_SIG: {
            status_ = Q_TRAN(&Table_paused);
            break;
        }
        default: {
            status_ = Q_SUPER(&Table_active);
            break;
        }
    }
    return status_;
}
/*${AOs::Table::SM::active::paused} ........................................*/
static QState Table_paused(Table * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Table::SM::active::paused} */
        case Q_ENTRY_SIG: {
            BSP_displayPaused(1U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Table::SM::active::paused} */
        case Q_EXIT_SIG: {
            BSP_displayPaused(0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Table::SM::active::paused::SERVE} */
        case SERVE_SIG: {
            status_ = Q_TRAN(&Table_serving);
            break;
        }
        /*${AOs::Table::SM::active::paused::HUNGRY} */
        case HUNGRY_SIG: {
            uint8_t n = (uint8_t)Q_PAR(me);

            BSP_displayPhilStat(n, "hungry  ");

            /* philo ID must be in range and he must be not hungry */
            Q_ASSERT((n < N_PHILO) && (me->isHungry[n] == 0U));
            me->isHungry[n] = 1U;
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Table::SM::active::paused::DONE} */
        case DONE_SIG: {
            uint8_t n, m;

            n = (uint8_t)Q_PAR(me);
            /* philo ID must be in range and he must be not hungry */
            Q_ASSERT((n < N_PHILO) && (me->isHungry[n] == 0U));

            BSP_displayPhilStat(n, "thinking");
            m = LEFT(n);
            /* both forks of Phil[n] must be used */
            Q_ASSERT((me->fork[n] == USED) && (me->fork[m] == USED));

            me->fork[m] = FREE;
            me->fork[n] = FREE;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Table_active);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Table} #####################################################*/
/*$define${AOs::Table_ctor} ################################################*/
/*${AOs::Table_ctor} .......................................................*/
static void Table_ctor(void) {
    uint8_t n;
    Table *me = &AO_Table;

    QActive_ctor(&me->super, Q_STATE_CAST(&Table_initial));
    for (n = 0U; n < N_PHILO; ++n) {
        Philo_ctor(&me->philo_pool[n], n);
        me->fork[n] = FREE;
        me->isHungry[n] = 0U;
    }
}
/*$enddef${AOs::Table_ctor} ################################################*/
//...

